In [ ]:
Question 3(B): Perform Matrix Manipulation on Stock Price Data
Problem Statement:
A stock analyst is analyzing two stocks using their daily price data recorded over a week.
Each stock's data is represented as a 5x3 matrix, where:
● Each row represents a day (5 days in total).
● Each column represents a different price feature: Open, High, and Low.
Write a Python program to:
● Compute the element-wise sum of the two matrices to analyze combined price
values.
● Compute the element-wise difference to understand the daily spread between the
two stocks.
Use NumPy for matrix operations.

In [1]:
import numpy as np

# Generate random stock price matrices (5 days × 3 features)
stockA = np.random.randint(90, 120, (5,3))
stockB = np.random.randint(90, 120, (5,3))

print("Stock A Data:\n", stockA)
print("\nStock B Data:\n", stockB)

# Element-wise sum
sum_matrix = stockA + stockB

# Element-wise difference
diff_matrix = stockA - stockB

print("\nElement-wise Sum:\n", sum_matrix)
print("\nElement-wise Difference:\n", diff_matrix)

Stock A Data:
 [[111 109 113]
 [112 119 115]
 [116 111 106]
 [118  97 117]
 [103  94 100]]

Stock B Data:
 [[100 103  90]
 [119  93 100]
 [108  97  90]
 [105 100 118]
 [119 105 105]]

Element-wise Sum:
 [[211 212 203]
 [231 212 215]
 [224 208 196]
 [223 197 235]
 [222 199 205]]

Element-wise Difference:
 [[ 11   6  23]
 [ -7  26  15]
 [  8  14  16]
 [ 13  -3  -1]
 [-16 -11  -5]]
