In [ ]:
Question 2(B) : Analyze Student Grades Using NumPy
Problem Statement:
Write a Python program using NumPy to analyze the grades of 30 students across three
subjects: Math, Science, and English. Your program should:
● Calculate overall and subject-wise statistics such as average, highest, and lowest
grades.
● Identify top-performing students based on total or average scores.
● Optionally visualize the grade distributions for each subject using histograms or bar
charts.

In [1]:
import numpy as np

grades = np.random.randint(50, 100, size=(30,3))   # 30 students, 3 subjects, grades between 50 and 100

print("Grades Matrix:\n", grades)

print("Subject Average:", grades.mean(axis=0))
print("Highest Marks:", grades.max())
print("Lowest Marks:", grades.min())

total = grades.sum(axis=1)
top_student = total.argmax()

print("Top Student Index:", top_student)

Grades Matrix:
 [[52 52 58]
 [79 76 77]
 [70 81 74]
 [89 71 87]
 [68 55 83]
 [71 77 76]
 [95 88 83]
 [70 57 73]
 [69 59 66]
 [88 65 60]
 [84 89 74]
 [80 95 79]
 [71 81 69]
 [67 54 93]
 [54 88 54]
 [73 57 67]
 [92 62 63]
 [74 78 66]
 [62 60 67]
 [99 98 90]
 [87 74 96]
 [78 97 62]
 [81 86 96]
 [97 61 84]
 [83 50 95]
 [81 90 69]
 [62 73 76]
 [51 97 97]
 [97 75 74]
 [54 59 69]]
Subject Average: [75.93333333 73.5        75.9       ]
Highest Marks: 99
Lowest Marks: 50
Top Student Index: 19
